In [1]:
import pandas as pd

In [53]:
df = pd.read_csv('sales_data.csv', header = 0, index_col=False)
df.head(20)

/tmp/ipython-input-3411753184.py:1: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df = pd.read_csv('sales_data.csv', header = 0, index_col=False)

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,1001.0,USB-C Cable,2.0,11.95,01/01/23 10:00,917 1st St
1,1002.0,Macbook Pro Laptop,1.0,1700.00,01/02/23 12:00,682 Chestnut St
2,1003.0,USB-C Cable,1.0,NaN,01/05/23 11:30,123 Main St
3,1004.0,AAA Batteries (4-pack),3.0,2.99,01/10/23 09:15,456 Elm St
4,NaN,NaN,NaN,NaN,NaN,NaN
5,1005.0,AAA Batteries (4-pack),2.0,2.99,2023-02-01 14:00,789 Maple St
6,1006.0,ThinkPad Laptop,1.0,999.99,02/05/23 16:20,321 Oak St
7,1007.0,USB-C Cable,1.0,11.95,02/10/23 08:45,654 Pine St
8,1008.0,ThinkPad Laptop,1.0,NaN,02/15/23 13:00,987 Cedar St
9,1009.0,Lightning Cable,1.0,14.95,03/01/23 10:00,111 Birch St
10,1010.0,Lightning Cable,3.0,14.95,03/05/23 12:30,222 Walnut St
11,1011.0,AAA Batteries (4-pack),1.0,2.99,03/10/23 15:45,333 Cherry St

In [54]:
df.dropna(subset=['Order ID', 'Product'], inplace=True)
df.head(15)

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,1001.0,USB-C Cable,2.0,11.95,01/01/23 10:00,917 1st St
1,1002.0,Macbook Pro Laptop,1.0,1700.00,01/02/23 12:00,682 Chestnut St
2,1003.0,USB-C Cable,1.0,NaN,01/05/23 11:30,123 Main St
3,1004.0,AAA Batteries (4-pack),3.0,2.99,01/10/23 09:15,456 Elm St
5,1005.0,AAA Batteries (4-pack),2.0,2.99,2023-02-01 14:00,789 Maple St
6,1006.0,ThinkPad Laptop,1.0,999.99,02/05/23 16:20,321 Oak St
7,1007.0,USB-C Cable,1.0,11.95,02/10/23 08:45,654 Pine St
8,1008.0,ThinkPad Laptop,1.0,NaN,02/15/23 13:00,987 Cedar St
9,1009.0,Lightning Cable,1.0,14.95,03/01/23 10:00,111 Birch St
10,1010.0,Lightning Cable,3.0,14.95,03/05/23 12:30,222 Walnut St
11,1011.0,AAA Batteries (4-pack),1.0,2.99,03/10/23 15:45,333 Cherry St

In [55]:
df['Price Each'] = df['Price Each'].fillna(
    df.groupby('Product')['Price Each'].transform('mean')
)
df

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,1001.0,USB-C Cable,2.0,11.95,01/01/23 10:00,917 1st St
1,1002.0,Macbook Pro Laptop,1.0,1700.00,01/02/23 12:00,682 Chestnut St
2,1003.0,USB-C Cable,1.0,11.95,01/05/23 11:30,123 Main St
3,1004.0,AAA Batteries (4-pack),3.0,2.99,01/10/23 09:15,456 Elm St
5,1005.0,AAA Batteries (4-pack),2.0,2.99,2023-02-01 14:00,789 Maple St
6,1006.0,ThinkPad Laptop,1.0,999.99,02/05/23 16:20,321 Oak St
7,1007.0,USB-C Cable,1.0,11.95,02/10/23 08:45,654 Pine St
8,1008.0,ThinkPad Laptop,1.0,999.99,02/15/23 13:00,987 Cedar St
9,1009.0,Lightning Cable,1.0,14.95,03/01/23 10:00,111 Birch St
10,1010.0,Lightning Cable,3.0,14.95,03/05/23 12:30,222 Walnut St
11,1011.0,AAA Batteries (4-pack),1.0,2.99,03/10/23 15:45,333 Cherry St

In [91]:
df['Order Date'] = pd.to_datetime(df['Order Date'], format='%d/%m/%Y', errors='coerce')
df['Order Date'].dtype

dtype('<M8[ns]')

In [92]:
df['Total_Sales'] = df['Quantity Ordered'] * df['Price Each']
df.head(11)

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Total_Sales
0,1001.0,USB-C Cable,2.0,11.95,2023-01-01,917 1st St,23.90
1,1002.0,Macbook Pro Laptop,1.0,1700.00,2023-01-02,682 Chestnut St,1700.00
2,1003.0,USB-C Cable,1.0,11.95,2023-01-05,123 Main St,11.95
3,1004.0,AAA Batteries (4-pack),3.0,2.99,2023-01-10,456 Elm St,8.97
5,1005.0,AAA Batteries (4-pack),2.0,2.99,2023-02-01,789 Maple St,5.98
6,1006.0,ThinkPad Laptop,1.0,999.99,2023-02-05,321 Oak St,999.99
7,1007.0,USB-C Cable,1.0,11.95,2023-02-10,654 Pine St,11.95
8,1008.0,ThinkPad Laptop,1.0,999.99,2023-02-15,987 Cedar St,999.99
9,1009.0,Lightning Cable,1.0,14.95,2023-03-01,111 Birch St,14.95
10,1010.0,Lightning Cable,3.0,14.95,2023-03-05,222 Walnut St,44.85
11,1011.0,AAA Batteries (4-pack),1.0,2.99,2023-03-10,333 Cherry St,2.99

In [93]:
df_grouped = df.groupby(df['Order Date'].dt.strftime('%b'))['Total_Sales'].sum()
df_grouped.head(5)

Order Date
Feb    2017.91
Jan    1744.82
Mar      62.79
Name: Total_Sales, dtype: float64

In [114]:
df_grouped_qty = df.groupby([df['Order Date'].dt.strftime('%Y-%m'),df['Product']])['Quantity Ordered'].sum()
df_grouped_qty.head(12)

max_products_per_month = df_grouped_qty.groupby(level=0).idxmax()
max_products_per_month

Order Date
2023-01    (2023-01, AAA Batteries (4-pack))
2023-02    (2023-02, AAA Batteries (4-pack))
2023-03           (2023-03, Lightning Cable)
Name: Quantity Ordered, dtype: object

In [115]:
print("--------MONTHLY REPORT-------------")
print(df_grouped)
print("--------BEST SELLING PRODUCT PER MONTH-------------")
print(max_products_per_month)

--------MONTHLY REPORT-------------
Order Date
Feb    2017.91
Jan    1744.82
Mar      62.79
Name: Total_Sales, dtype: float64
--------BEST SELLING PRODUCT PER MONTH-------------
Order Date
2023-01    (2023-01, AAA Batteries (4-pack))
2023-02    (2023-02, AAA Batteries (4-pack))
2023-03           (2023-03, Lightning Cable)
Name: Quantity Ordered, dtype: object

In [117]:
df.to_csv('cleaned_sales.csv')